### ISSUE TITLE
What does pier's core offer over vanilla shake?

### ISSUE THREAD

**Issue by chreekat** [judah/pier#137]
> Pier layers its Haskell-specific logic on top of a general-purpose library for hermetic, parallel builds and dependency tracking. 

Isn't shake already a "general-purpose library for hermetic, parallel builds and dependency tracking"? :) What have you added?

I'm just asking because I think the idea behind pier—using shake instead of stack or cabal to do the actual building—seems really promising, and I'm curious to know what makes pier tick.

**Comment by judah** [comment]
In short, the "hermetic" attribute is where Pier differs from Shake.  In particular:

- Shake-the-library makes no explicit decisions about the organization of output files.  In contrast, Pier organizes the output of each action in a [hash-addressed directory](https://github.com/judah/pier#build-outputs). 
- In Shake, declaring a file requirement (`need`) and using it (`cmd`) are separates actions, and if you miss a `need` then Shake might not rebuild everything aggressively enough.  In contrast, Pier runs each build action (`Command`) in its own temporary directory, and the only files available for that command to use are those declared with `input` (Pier's equivalent of `need`).  So if you miss a `input`, the command will fail the very first time you try to run it.

The motivation is similar to, e.g., Bazel or Nix versus Make.  Another useful reference describing this more: https://www.tweag.io/posts/2018-03-15-bazel-nix.html

**Comment by chreekat** [comment]
Thanks! That makes a lot of sense.
